### ISSUE TITLE
Recorded video shows black screen only when it is done on a Windows VM which is minimized

### ISSUE THREAD

**Issue by dsushanta** [tuenti/VideoRecorderService#1]
Hi,
I was trying to integrate this service with my UI automation framework with selenium grid.
In my framework the UI tests get executed on one of my windows VMs.
I wanted to record a video for the test execution which is going on my Windows VM.
I have followed the steps mentioned and executed all the commands on my Windows VM to bring up the REST services.
I sent a GET request to /rec/start to start recording. I started my selenium scripts. Once my execution got over, I sent a GET request to /rec/save/test to stop and save the video.
The video file got generated properly but it was totally dark.
I think I have figured out the reason - My remote desktop session to my Windows VM was always minimized. So it came all dark.
Is there a way to record the video properly even if the remote desktop session of my Windows VM is minimized ?
Any quick help is greatly appreciated. 
Thanks in Advance

**Comment by nimeacuerdo** [comment]
Hi @dsushanta, we are using this service in our CI infrastructure where Windows VMs are spawned without anyone opening remote desktop sessions against them (we did in the past for debugging purposes), so I can't really tell you if there's a problem with that.
